version: '3'

services:
  jekyll:
    build: .
    volumes:
      - .:/srv/jekyll
      - jekyll-bundle:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll-bundle:
